name: Deploy Main Branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Code to Lambda
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Install AWS CLI
      run: |
          sudo apt-get install -y awscli
          aws --version
    - name: Zip Code
      run: |
          rm -f code.zip
          zip ./code.zip ./*

    - name: Sync with S3
      run: |
          aws s3 sync ./code.zip s3://${{ secrets.AWS_BUCKET_NAME }}
          echo '${{ secrets.AWS_BUCKET_NAME }}'

    # - name: serverless deploy
    #   uses: serverless/github-action@v3.2
    #   with:
    #     args: deploy --region ${{ secrets.AWS_REGION }}
    #   env:
    #     SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}