name: Deploy Main Branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Code to Lambda
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Install AWS CLI
      run: |
          sudo apt-get install -y awscli
          aws --version
    - name: Zip Code
      run: |
          export CODE_VERSION=$(date -u +"%Y-%m-%dT%H:%M:%S")
          zip ./zip_files/code_${CODE_VERSION}.zip ./*
    - name: Sync with S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
          aws s3 sync zip_files s3://${{ secrets.AWS_BUCKET_NAME }}/zip_files --region ${{ secrets.AWS_REGION }}
          aws s3 sync cloudformation s3://${{ secrets.AWS_BUCKET_NAME }}/cloudformation --region ${{ secrets.AWS_REGION }}
          aws cloudformation create-stack --capabilities CAPABILITY_IAM \
          --stack-name STACK_${CODE_VERSION} \
          --template-body s3://${{ secrets.AWS_BUCKET_NAME }}/cloudformation/cloudformation.yml \
          --parameters ParameterKey=VERSION,ParameterValue=${CODE_VERSION}
